#!/usr/bin/env julia

using LoadLeveller
using LoadLeveller.JobTools
using Ising

tm = TaskMaker()
tm.thermalization = 10000
tm.sweeps = 10000
tm.binsize = 1

Lxs = [10, 20]
Ts = range(1, 4, length=10)

# parameters need not be numbers
tm.test = [1, 2, 3, 4]

for Lx in Lxs
    for T in Ts
        # every call to task() will turn into one task which has
        # the current state of the parameter set.
        # You could also write
        #
        # tm.Lx = Lx
        # tm.T = T
        # tm.task()
        
        task(tm, Lx=Lx, T=T)
    end
end

job = JobInfo(
    @__FILE__,
    Ising.MC;
    tasks = make_tasks(tm),
    checkpoint_time = "30:00",
    run_time = "24:00:00"
)

LoadLeveller.start(job, ARGS)